version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - MongoVolume:/data/db
    networks:
      - taw-subnet 

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./Backend:/app/Backend
    networks:
      - taw-subnet  

  frontend:
    build: ./Frontend/restaurant
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - backend
    networks:
      - taw-subnet  

networks:
  taw-subnet:
    external: true

volumes:
  MongoVolume: